// Package user Code generated by swaggo/swag. DO NOT EDIT
package user

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Reoden",
            "url": "https://github.com/Reoden"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/user/captcha": {
            "post": {
                "description": "send user captcha",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "send user captcha",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "SendCaptchaRequestDto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.SendCaptchaRequestDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.SendCaptchaResponseDto"
                        }
                    }
                }
            }
        },
        "/api/v1/user/loginuser": {
            "post": {
                "description": "user loginuser check",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "user loginuser",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "LoginUserRequestDto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.LoginUserRequestDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.LoginUserResponseDto"
                        }
                    }
                }
            }
        },
        "/api/v1/user/logout": {
            "post": {
                "description": "user logoutuser check",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "user logoutuser",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "LogoutUserRequestDto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.LogoutUserRequestDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.LogoutUserResponseDto"
                        }
                    }
                }
            }
        },
        "/api/v1/user/register": {
            "post": {
                "description": "Create new user item",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Create user",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "CreateUserRequestDto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateUserRequestDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateUserResponseDto"
                        }
                    }
                }
            }
        },
        "/api/v1/user/{user_id}": {
            "get": {
                "description": "Find user item by UserId",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Find user By UserId",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "FindUserByIdRequestDto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.FindUserByIdRequestDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dtos.FindUserByIdResponseDto"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dtos.CreateUserRequestDto": {
            "type": "object",
            "properties": {
                "captcha": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "dtos.CreateUserResponseDto": {
            "type": "object",
            "properties": {
                "userID": {
                    "type": "string"
                }
            }
        },
        "dtos.FindUserByIdRequestDto": {
            "type": "object",
            "properties": {
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dtos.FindUserByIdResponseDto": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/v1.UserDto"
                }
            }
        },
        "dtos.LoginUserRequestDto": {
            "type": "object",
            "properties": {
                "captcha": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "dtos.LoginUserResponseDto": {
            "type": "object",
            "properties": {
                "userId": {
                    "type": "string"
                }
            }
        },
        "dtos.LogoutUserRequestDto": {
            "type": "object"
        },
        "dtos.LogoutUserResponseDto": {
            "type": "object"
        },
        "dtos.SendCaptchaRequestDto": {
            "type": "object",
            "properties": {
                "phone": {
                    "type": "string"
                }
            }
        },
        "dtos.SendCaptchaResponseDto": {
            "type": "object"
        },
        "v1.UserDto": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "User Service Api",
	Description:      "User Service Api.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
